version: 2
jobs:
  build:
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    docker:
      - image: cimg/base:2023.09
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get -y install locales make
            sudo apt-get -y install util-linux bsdmainutils gawk curl rlwrap emacs
      - run:
          name: Sanity Check
          command: |
            make test
